version: 0.2

env:
  secrets-manager:
    AWS_ACCESS_KEY_ID: prod/amplify-s3-pipeline-buildkey:aws_access_key_id
    AWS_SECRET_ACCESS_KEY: prod/amplify-s3-pipeline-buildkey:aws_secret_access_key
  
phases:
  build:
    commands:
       - npm install -g @aws-amplify/cli
       - chmode a+x headless-configure.sh
       - chmod a+x headless-publish.sh
       - ./headless-configure.sh
       - ./headless-publish.sh